#!/usr/bin/env perl

use strict;
use warnings;

#
# Due to a bug there are temp files in the home folder
# on Ubuntu 12.04, this script removes them
#

main();

sub main {
    my $home_folder               = $ENV{'HOME'};
    my @files_staged_for_deletion = glob "${home_folder}/.goutputstream-*";

    for (@files_staged_for_deletion) {
        unlink $_ or die "Cannot remove $_: $!\n";
    }
}
