#!/bin/bash

echo -e "\033[1;32m
\033[0;33m####################: \033[0;37mSystem Data\033[0;33m :######################
#      \033[0;37mHostname \033[0;33m= \033[1;32m`hostname`
\033[0;33m#     \033[0;37mPublic IP \033[0;33m= \033[1;32m`/sbin/ifconfig | grep -i "inet addr" | grep -v "127.0.0.1" | sed 's/^[[:space:]]*//' | sed 's/:/ /' | awk '{ print $3 }' | head -1`
\033[0;33m#        \033[0;37mKernel \033[0;33m= \033[1;32m`uname -r`
\033[0;33m#        \033[0;37mUptime \033[0;33m= \033[1;32m`let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"; let secs=$((${upSeconds}%60)); let mins=$((${upSeconds}/60%60)); let hours=$((${upSeconds}/3600%24)); let days=$((${upSeconds}/86400)); printf "%dd %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`
\033[0;33m#    \033[0;37mCPU Family \033[0;33m= \033[1;32m`cat /proc/cpuinfo | grep -i "model name" | wc -l` x `cat /proc/cpuinfo | grep -i "model name" | sed 's/model name//' | sed 's/://' | sed 's/^[[:space:]]*//' | uniq`
\033[0;33m#    \033[0;37mUsable RAM \033[0;33m= \033[1;32m`cat /proc/meminfo | grep -i "memtotal" | awk {'print $2'}` kB
\033[0;33m#    \033[0;37mRoot Usage \033[0;33m= \033[1;32m`df -h | grep "/$" | awk '{ print $(NF-1), $NF }'`
\033[0;33m#     \033[0;37mLoad Avg. \033[0;33m= \033[1;32m`uptime | awk '{print $(NF-2),$(NF-1),$NF}'`
\033[0;33m#     \033[0;37mCPU Usage \033[0;33m= \033[1;32m`A=$(uptime | awk '{ print $NF }') && B=$(cat /proc/cpuinfo | grep -i "model name" | wc -l) && bc <<< "scale = 4; (($A / $B) * 100)"` %
\033[0;33m#  \033[0;37mMemory Usage \033[0;33m= \033[1;32m`free -m | grep -i "buffers" | grep -i -v "total" | awk '{ print $3/($3+$4)*100 }'` %
\033[0;33m#      \033[0;37mCPU temp \033[0;33m= \033[1;32m`sensors |grep temp1 |awk '{print $2}'`
\033[0;33m######################: \033[0;37mUser Data\033[0;33m :######################
#      \033[0;37mUsername \033[0;33m= \033[1;32m`whoami`
\033[0;33m#         \033[0;37mUsers \033[0;33m= \033[1;32m`w | grep -i -v "load average" | grep -i -v "login@" | wc -l`
\033[0;33m#     \033[0;37mHome Dir. \033[0;33m= \033[1;32m`echo $HOME`
\033[0;33m#########################################################"

echo
